name: Chat front end CD
on: 
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
jobs:
  deploy:
    name: Deploy To Digital Ocean
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.CHAT_FRONTEND_HOST }}
      USER: ${{ secrets.CHAT_FRONTEND_HOST_USER }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-node@v3
        with:
          node-version: 16.13

      - name: Create .env
        run: |
          echo REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }} > ./.env
          echo REACT_APP_BASE_WEBSOCKET_URL=${{ secrets.REACT_APP_BASE_WEBSOCKET_URL }} >> ./.env
      - name: install yarn
        run: npm install --global yarn
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn build
      - name: deploy
        run: |
          echo "${{ secrets.CHAT_FRONTEND_SSH_KEY }}" > ssh-key.pem
          chmod 600 ./ssh-key.pem
          eval $(ssh-agent)
          ssh-add ./ssh-key.pem
          scp -o StrictHostKeyChecking=no -r ./build/* "$USER"@"$HOST":/var/www/$HOST/html
